services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    volumes:
      - .:/app
    ports:
      - "28080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=user
      - DB_PASSWORD=pass
      - DB_NAME=local
    command: air -c .air.toml

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: local
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "23306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
